apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

#namePrefix: dev-
commonLabels:
  variant: development


# replace the image tag of the container with latest
images:
- digest: sha256:ac61c247578acbe30d1348bbed9442d753eb70bb8533638719c50e78143baa0c
  name: quay.io/rohanp/newdemo:latest
  newName: quay.io/rohanp/newdemo:latest

# generate a configmap 
configMapGenerator:
- literals:
  - APP_GREETING=Hello gitOps interested people! Hope you like it!
  name: app-config

# This patch provides the name of the namespace into the env-value of the Job
# This is needed because we want to call the target rest service of person-service
# which is: person-service.$NAMESPACE.svc:8080
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: book-dev
  target:
    kind: Job
